#!/usr/bin/env node
// Import the 9 songs of the Effects repo (github.com/goldshoot0720/Effects) for the PVs:
// copies Effects/audio/<id>.mp3 → audio/ and writes js/pv/songs-data.js with the timed
// lyrics, sections, analysed BPM / first beat and the loudness envelope.
// Usage: node tools/import-songs.mjs [path/to/Effects]
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SRC = path.resolve(process.argv[2] || path.join(ROOT, '..', 'Effects'));
const ctx = { window: {} };
vm.createContext(ctx);
const dir = path.join(SRC, 'data', 'song');
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.js')).sort();
for (const f of files) vm.runInContext(fs.readFileSync(path.join(dir, f), 'utf8'), ctx);

fs.mkdirSync(path.join(ROOT, 'audio'), { recursive: true });
const out = {};
for (const [id, s] of Object.entries(ctx.window.MV_SONG_DATA)) {
  const a = s.analysis;
  fs.copyFileSync(path.join(SRC, s.audio), path.join(ROOT, 'audio', `${id}.mp3`));
  out[id] = {
    id, title: s.title, tagline: s.tagline, credit: s.cast, theme: s.theme, audio: `audio/${id}.mp3`,
    dur: a.duration, bpm: a.bpm, beat0: a.beat0, rmsFps: a.rmsFps, rms: a.rms,
    sections: s.sections.map(({ kind, start, end }) => ({ kind, start, end })),
    lines: s.lines.map(({ t, d, text, sec, kind }) => ({ t, d, text, sec, kind })),
  };
  console.log(`${id} ${s.title}  ${a.duration.toFixed(1)}s  ${a.bpm} BPM  ${s.lines.length} lines`);
}
fs.writeFileSync(path.join(ROOT, 'js', 'pv', 'songs-data.js'),
  `// generated by tools/import-songs.mjs from the Effects repo — do not edit by hand\nexport const SONG_DATA = ${JSON.stringify(out)};\n`);
